FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt \
    && pip uninstall -y apache-airflow apache-airflow-providers-google || true
COPY src ./src
ENV PORT=8080
CMD ["uvicorn", "src.serving.app:app", "--host", "0.0.0.0", "--port", "8080"]
