FROM python:3.12-slim
WORKDIR /app
# Faster installs by caching wheels
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY src ./src

ENV PYTHONUNBUFFERED=1
CMD ["python", "-m", "src.models.train"]